version: "3.8"

services:
  tg-php:
    container_name: tg-php
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./../:/var/www/
    ports:
      - ${PORT}:8080

volumes:
  db_data: